#!/bin/bash

echo "=== Configuring git ==="
read -p "Enter your user.name of git: " username
read -p "Enter your user.email of git: " email
git config --global user.name $username
git config --global user.email $email
git config --global alias.co checkout
git config --global alias.br branch
git config --global alias.ci commit
git config --global alias.st status
git config --global alias.last 'log -1 HEAD'
git config --global alias.unstage 'reset HEAD --'
git config --global alias.last 'log -1 HEAD'
git config --global alias.llog 'log --date=local'
git config --global alias.flog 'log --pretty=fuller --decorate'
git config --global alias.lg "log --graph --pretty=format:'%Cred%h%Creset -%C(yellow)%d%Creset %s %Cgreen(%cr) %C(bold blue)<%an>%Creset' --abbrev-commit --date=relative"
git config --global alias.lol 'log --graph --decorate --oneline'
git config --global alias.lola 'log --graph --decorate --oneline --all'
git config --global alias.blog 'log origin/master... --left-right'
