#!/bin/bash

latestVersion=$(curl "https://www.jetbrains.com/updates/updates.xml" | xmllint --format --xpath 'string(/products/product[@name="IntelliJ IDEA"]/channel[@name="IntelliJ IDEA RELEASE"]/build/@version)' -)
echo "The latest Intellij Ultimate version is $latestVersion"
curl "https://download-cdn.jetbrains.com/idea/ideaIU-$latestVersion.tar.gz" -o /tmp/intellij.tar.gz
mkdir -p ~/Applications
tar -xvf /tmp/intellij.tar.gz -C ~/Applications

