#!/bin/bash

echo "============ Installing zsh ============"
sudo dnf install zsh -y
echo "============ Installing oh-my-zsh ============"
sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" "" --unattended

echo "===Installing oh-my-zsh plugins==="
# zsh-autosuggestions
git clone https://github.com/zsh-users/zsh-autosuggestions ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-autosuggestions
# zsh-syntax-highlighting
git clone https://github.com/zsh-users/zsh-syntax-highlighting.git ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-syntax-highlighting
# dirhistory
mkdir ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/dirhistory
curl https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/plugins/dirhistory/dirhistory.plugin.zsh -o ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/dirhistory/dirhistory.plugin.zsh 
# history
mkdir ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/history
curl https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/plugins/history/history.plugin.zsh -o ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/history/history.plugin.zsh 
# powerlevel10k/powerlevel10k
git clone --depth=1 https://github.com/romkatv/powerlevel10k.git ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/themes/powerlevel10k
sed -i -e "s/plugins=(git)/plugins=(git\ zsh-autosuggestions\ zsh-syntax-highlighting\ dirhistory\ history)/g" -e 's/ZSH_THEME="robbyrussell"/ZSH_THEME="powerlevel10k\/powerlevel10k"/g' ~/.zshrc 

