#!/bin/bash

echo "You are using Fedora OS, verifying if the OS is updated"
sudo dnf check-update
returnCode=$?
if [ $returnCode -eq 0 ]; then
    echo "OK"
elif [ $returnCode -eq 100 ]; then
    echo "The OS is not updated, execute [ sudo dnf update ] and restart before running this script"
    #exit $returnCode 
else 
    echo "Error verifying OS, execute [ sudo dnf check-update ] to see details"
    exit $returnCode
fi
echo "============ Adding Flatpak repository ============"
flatpak remote-add --if-not-exists flathub https://dl.flathub.org/repo/flathub.flatpakrepo

echo "============ Installing useful apps ============"
# 1password
curl https://downloads.1password.com/linux/rpm/stable/x86_64/1password-latest.rpm -o /tmp/1password.rpm
sudo dnf localinstall /tmp/1password.rpm -y


#vscode copyq gnome-tweaks
sudo rpm --import https://packages.microsoft.com/keys/microsoft.asc
sudo sh -c 'echo -e "[code]\nname=Visual Studio Code\nbaseurl=https://packages.microsoft.com/yumrepos/vscode\nenabled=1\ngpgcheck=1\ngpgkey=https://packages.microsoft.com/keys/microsoft.asc" > /etc/yum.repos.d/vscode.repo'
sudo dnf install code copyq tilix gnome-tweaks -y

bash intellij
bash flatpak-apps
bash node
bash git
#bash shortcuts
bash oh-my-zsh
bash config-tilix
bash github

Green='\033[0;32m' 
NC='\033[0m'
echo ""
echo "Zsh is installed but is not your default shell yet"
echo "Run:"
echo -e "${Green}	chsh -s \$(which zsh)${NC}"
echo ""
echo "and logout to make zsh default"
#todo config copyq tilix security and timeshift

