#!/bin/bash

echo "You are using Fedora OS, verifying if the OS is updated"
sudo dnf check-update
returnCode=$?
if [ $returnCode -eq 0 ]; then
    echo "OK"
elif [ $returnCode -eq 100 ]; then
    echo "The OS is not updated, execute [ sudo dnf update ] and restart before running this script"
    exit $returnCode 
else 
    echo "Error verifying OS, execute [ sudo dnf check-update ] to see details"
    exit $returnCode
fi
echo ">=== Adding Flatpak repository ==="
flatpak remote-add --if-not-exists flathub https://dl.flathub.org/repo/flathub.flatpakrepo

echo "=== Installing zsh ==="
sudo dnf install zsh -y


echo "=== Installing useful apps ==="
# 1password
curl https://downloads.1password.com/linux/rpm/stable/x86_64/1password-latest.rpm -o /tmp/1password.rpm
sudo dnf localinstall /tmp/1password.rpm -y


#vscode copyq gnome-tweaks
sudo rpm --import https://packages.microsoft.com/keys/microsoft.asc
sudo sh -c 'echo -e "[code]\nname=Visual Studio Code\nbaseurl=https://packages.microsoft.com/yumrepos/vscode\nenabled=1\ngpgcheck=1\ngpgkey=https://packages.microsoft.com/keys/microsoft.asc" > /etc/yum.repos.d/vscode.repo'
sudo dnf install code copyq tilix gnome-tweaks -y

# scripts without sudo
su -c "bash oh-my-zsh" $SUDO_USER
su -c "bash flatpak-apps" $SUDO_USER
su -c "bash node" $SUDO_USER
su -c "bash git" $SUDO_USER

#todo config copyq tilix
